import { IMG } from './constants/images';

const defaultDescription = (title: string, region: string) => [
  `${title} расположен в регионе: ${region}. Мост относится к важным транспортным сооружениям России.`,
  'Объект используется для связи районов и повышения пропускной способности дорожной или железнодорожной сети.',
];

const bridges = [
  { id: 1, img: IMG.krim, title: 'Крымский мост', region: 'Керченский пролив', year: 2018, length: 19.0, type: 'Авто + ЖД', capacity: 40 },
  { id: 2, img: IMG.russki, title: 'Русский мост', region: 'Приморский край', year: 2012, length: 3.1, type: 'Вантовый авто', capacity: 25 },
  { id: 3, img: IMG.obuhovski, title: 'Большой Обуховский', region: 'Санкт-Петербург', year: 2016, length: 2.8, type: 'Вантовый авто', capacity: 30 },
  { id: 4, img: IMG.amur, title: 'Амурский (Хабаровский)', region: 'Хабаровский край', year: 1999, length: 2.6, type: 'Авто + ЖД', capacity: 20 },
  { id: 5, img: IMG.russki, title: 'Уфимский мост', region: 'Башкортостан', year: 2001, length: 2.0, type: 'Авто', capacity: 15 },
  { id: 6, img: IMG.russki, title: 'Саратовский мост', region: 'Саратовская область', year: 1965, length: 2.8, type: 'Авто', capacity: 18 },
  { id: 7, img: IMG.president, title: 'Волжский мост', region: 'Ульяновская область', year: 2009, length: 5.8, type: 'Авто', capacity: 20 },
  { id: 8, img: IMG.russki, title: 'Южный мост', region: 'Новосибирск', year: 2014, length: 2.1, type: 'Авто', capacity: 25 },
  { id: 9, img: IMG.russki, title: 'Бугринский мост', region: 'Новосибирск', year: 2014, length: 2.1, type: 'Арочный авто', capacity: 20 },
  { id: 10, img: IMG.president, title: 'Президентский мост', region: 'Ульяновская область', year: 2009, length: 5.8, type: 'Авто', capacity: 22 },
  { id: 11, img: IMG.russki, title: 'Живописный мост', region: 'Москва', year: 2007, length: 1.5, type: 'Арочный авто', capacity: 35 },
  { id: 12, img: IMG.russki, title: 'Сургутский мост', region: 'Ханты-Мансийский АО', year: 2000, length: 2.1, type: 'Вантовый авто', capacity: 18 },
  { id: 13, img: IMG.russki, title: 'Коммунальный мост', region: 'Красноярск', year: 1961, length: 2.3, type: 'Авто', capacity: 15 },
  { id: 14, img: IMG.russki, title: 'Пермский метромост', region: 'Пермь', year: 1992, length: 1.7, type: 'Авто', capacity: 12 },
  { id: 15, img: IMG.russki, title: 'Мост через Каму', region: 'Воткинск - Чайковский', year: 2005, length: 1.6, type: 'Авто', capacity: 14 },
  { id: 16, img: IMG.russki, title: 'Северный мост', region: 'Ярославль', year: 2006, length: 1.0, type: 'Авто', capacity: 10 },
  { id: 17, img: IMG.russki, title: 'Мост через Томь', region: 'Кемерово', year: 2013, length: 1.2, type: 'Авто', capacity: 15 },
  { id: 18, img: IMG.russki, title: 'Мост через Белую', region: 'Уфа', year: 1962, length: 1.2, type: 'Авто', capacity: 10 },
  { id: 19, img: IMG.russki, title: 'Сормовский мост', region: 'Нижний Новгород', year: 1981, length: 1.3, type: 'Авто', capacity: 12 },
  { id: 20, img: IMG.golden, title: 'Золотой мост', region: 'Владивосток', year: 2012, length: 1.4, type: 'Вантовый авто', capacity: 20 },
  { id: 21, img: IMG.russki, title: 'Коммунальный мост', region: 'Омск', year: 1955, length: 1.9, type: 'Авто', capacity: 15 },
  { id: 22, img: IMG.russki, title: 'Металлургический мост', region: 'Челябинск', year: 1973, length: 1.2, type: 'Авто', capacity: 8 },
  { id: 23, img: IMG.russki, title: 'Железнодорожный мост через Лену', region: 'Якутия (план)', year: 'строится', length: 3.0, type: 'ЖД', capacity: null },
  { id: 24, img: IMG.russki, title: 'Красноармейский мост', region: 'Волгоград', year: 1967, length: 1.1, type: 'Авто', capacity: 10 },
  { id: 25, img: IMG.russki, title: 'Коммунальный мост', region: 'Барнаул', year: 1967, length: 1.3, type: 'Авто', capacity: 9 },
  { id: 26, img: IMG.russki, title: 'Мост через Обь', region: 'Новосибирск', year: 1985, length: 2.1, type: 'Авто', capacity: 18 },
  { id: 27, img: IMG.russki, title: 'Кузнецкий мост', region: 'Новокузнецк', year: 1982, length: 1.4, type: 'Авто', capacity: 12 },
  { id: 28, img: IMG.russki, title: 'Мост через Иртыш', region: 'Омск', year: 1967, length: 1.8, type: 'Авто', capacity: 14 },
  { id: 29, img: IMG.russki, title: 'Томский мост', region: 'Томск', year: 1999, length: 1.6, type: 'Авто', capacity: 16 },
  { id: 30, img: IMG.russki, title: 'Мост через Ангару', region: 'Иркутск', year: 1978, length: 1.2, type: 'Авто', capacity: 10 },
  { id: 31, img: IMG.russki, title: 'Мост через Лену', region: 'Якутск', year: 1963, length: 1.0, type: 'Авто', capacity: 8 },
  { id: 32, img: IMG.russki, title: 'Мост через Амур', region: 'Благовещенск', year: 2009, length: 1.5, type: 'Авто', capacity: 12 },
  { id: 33, img: IMG.russki, title: 'Мост через Зею', region: 'Благовещенск', year: 1981, length: 1.1, type: 'Авто', capacity: 9 },
  { id: 34, img: IMG.russki, title: 'Мост через Уссури', region: 'Хабаровск', year: 1976, length: 1.3, type: 'Авто', capacity: 11 },
  { id: 35, img: IMG.russki, title: 'Мост через Бикин', region: 'Хабаровский край', year: 1988, length: 0.9, type: 'Авто', capacity: 7 },
  { id: 36, img: IMG.russki, title: 'Мост через Бурею', region: 'Амурская область', year: 1992, length: 1.0, type: 'Авто', capacity: 8 },
  { id: 37, img: IMG.russki, title: 'Мост через Селенгу', region: 'Бурятия', year: 1974, length: 1.2, type: 'Авто', capacity: 9 },
  { id: 38, img: IMG.russki, title: 'Мост через Витим', region: 'Иркутская область', year: 1985, length: 0.8, type: 'Авто', capacity: 6 },
  { id: 39, img: IMG.russki, title: 'Мост через Нижнюю Тунгуску', region: 'Красноярский край', year: 1991, length: 1.4, type: 'Авто', capacity: 10 },
  { id: 40, img: IMG.russki, title: 'Мост через Подкаменную Тунгуску', region: 'Красноярский край', year: 1987, length: 1.1, type: 'Авто', capacity: 8 },
  { id: 41, img: IMG.russki, title: 'Мост через Ангару', region: 'Красноярск', year: 1972, length: 1.3, type: 'Авто', capacity: 11 },
  { id: 42, img: IMG.russki, title: 'Мост через Чулым', region: 'Томская область', year: 1995, length: 1.0, type: 'Авто', capacity: 7 },
  { id: 43, img: IMG.russki, title: 'Мост через Кеть', region: 'Томская область', year: 1989, length: 0.9, type: 'Авто', capacity: 6 },
  { id: 44, img: IMG.russki, title: 'Мост через Таз', region: 'Ямало-Ненецкий АО', year: 1993, length: 1.2, type: 'Авто', capacity: 9 },
  { id: 45, img: IMG.russki, title: 'Мост через Пур', region: 'Ямало-Ненецкий АО', year: 1986, length: 1.1, type: 'Авто', capacity: 8 },
  { id: 46, img: IMG.russki, title: 'Мост через Надым', region: 'Ямало-Ненецкий АО', year: 1990, length: 1.0, type: 'Авто', capacity: 7 },
  { id: 47, img: IMG.russki, title: 'Мост через Обь', region: 'Ханты-Мансийский АО', year: 1984, length: 1.5, type: 'Авто', capacity: 12 },
  { id: 48, img: IMG.russki, title: 'Мост через Иртыш', region: 'Ханты-Мансийский АО', year: 1979, length: 1.3, type: 'Авто', capacity: 10 },
  { id: 49, img: IMG.russki, title: 'Мост через Конду', region: 'Ханты-Мансийский АО', year: 1987, length: 1.1, type: 'Авто', capacity: 8 },
].map((bridge) => ({
  ...bridge,
  city: bridge.region,
  description: defaultDescription(bridge.title, bridge.region),
}));

export default bridges;
