window.bridgesData = [
  { name: "Крымский мост", region: "Керченский пролив", year: "2018", length: "19.0", type: "Авто + ЖД", capacity: "40" },
  { name: "Русский мост", region: "Приморский край", year: "2012", length: "3.1", type: "Вантовый авто", capacity: "25" },
  { name: "Большой Обуховский", region: "Санкт-Петербург", year: "2016", length: "2.8", type: "Вантовый авто", capacity: "30" },
  { name: "Амурский (Хабаровский)", region: "Хабаровский край", year: "1999", length: "2.6", type: "Авто + ЖД", capacity: "20" },
  { name: "Уфимский мост", region: "Башкортостан", year: "2001", length: "2.0", type: "Авто", capacity: "15" },
  { name: "Саратовский мост", region: "Саратовская область", year: "1965", length: "2.8", type: "Авто", capacity: "18" },
  { name: "Волжский мост", region: "Ульяновская область", year: "2009", length: "5.8", type: "Авто", capacity: "20" },
  { name: "Южный мост", region: "Новосибирск", year: "2014", length: "2.1", type: "Авто", capacity: "25" },
  { name: "Бугринский мост", region: "Новосибирск", year: "2014", length: "2.1", type: "Арочный авто", capacity: "20" },
  { name: "Президентский мост", region: "Ульяновская область", year: "2009", length: "5.8", type: "Авто", capacity: "22" },
  { name: "Живописный мост", region: "Москва", year: "2007", length: "1.5", type: "Арочный авто", capacity: "35" },
  { name: "Сургутский мост", region: "Ханты-Мансийский АО", year: "2000", length: "2.1", type: "Вантовый авто", capacity: "18" },
  { name: "Коммунальный мост", region: "Красноярск", year: "1961", length: "2.3", type: "Авто", capacity: "15" },
  { name: "Пермский метромост", region: "Пермь", year: "1992", length: "1.7", type: "Авто", capacity: "12" },
  { name: "Мост через Каму", region: "Воткинск – Чайковский", year: "2005", length: "1.6", type: "Авто", capacity: "14" },
  { name: "Северный мост", region: "Ярославль", year: "2006", length: "1.0", type: "Авто", capacity: "10" },
  { name: "Мост через Томь", region: "Кемерово", year: "2013", length: "1.2", type: "Авто", capacity: "15" },
  { name: "Мост через Белую", region: "Уфа", year: "1962", length: "1.2", type: "Авто", capacity: "10" },
  { name: "Сормовский мост", region: "Нижний Новгород", year: "1981", length: "1.3", type: "Авто", capacity: "12" },
  { name: "Золотой мост", region: "Владивосток", year: "2012", length: "1.4", type: "Вантовый авто", capacity: "20" },
  { name: "Коммунальный мост", region: "Омск", year: "1955", length: "1.9", type: "Авто", capacity: "15" },
  { name: "Металлургический мост", region: "Челябинск", year: "1973", length: "1.2", type: "Авто", capacity: "8" },
  { name: "Железнодорожный мост через Лену", region: "Якутия (план)", year: "2026", length: "3.0", type: "ЖД", capacity: "5" },
  { name: "Красноармейский мост", region: "Волгоград", year: "1967", length: "1.1", type: "Авто", capacity: "10" },
  { name: "Коммунальный мост", region: "Барнаул", year: "1967", length: "1.3", type: "Авто", capacity: "9" },
  { name: "Мост через Обь", region: "Новосибирск", year: "1985", length: "2.1", type: "Авто", capacity: "18" },
  { name: "Кузнецкий мост", region: "Новокузнецк", year: "1982", length: "1.4", type: "Авто", capacity: "12" },
  { name: "Мост через Иртыш", region: "Омск", year: "1967", length: "1.8", type: "Авто", capacity: "14" },
  { name: "Томский мост", region: "Томск", year: "1999", length: "1.6", type: "Авто", capacity: "16" },
  { name: "Мост через Ангару", region: "Иркутск", year: "1978", length: "1.2", type: "Авто", capacity: "10" },
  { name: "Мост через Лену", region: "Якутск", year: "1963", length: "1.0", type: "Авто", capacity: "8" },
  { name: "Мост через Амур", region: "Благовещенск", year: "2009", length: "1.5", type: "Авто", capacity: "12" },
  { name: "Мост через Зею", region: "Благовещенск", year: "1981", length: "1.1", type: "Авто", capacity: "9" },
  { name: "Мост через Уссури", region: "Хабаровск", year: "1976", length: "1.3", type: "Авто", capacity: "11" },
  { name: "Мост через Бикин", region: "Хабаровский край", year: "1988", length: "0.9", type: "Авто", capacity: "7" },
  { name: "Мост через Бурею", region: "Амурская область", year: "1992", length: "1.0", type: "Авто", capacity: "8" },
  { name: "Мост через Селенгу", region: "Бурятия", year: "1974", length: "1.2", type: "Авто", capacity: "9" },
  { name: "Мост через Витим", region: "Иркутская область", year: "1985", length: "0.8", type: "Авто", capacity: "6" },
  { name: "Мост через Нижнюю Тунгуску", region: "Красноярский край", year: "1991", length: "1.4", type: "Авто", capacity: "10" },
  { name: "Мост через Подкаменную Тунгуску", region: "Красноярский край", year: "1987", length: "1.1", type: "Авто", capacity: "8" },
  { name: "Мост через Ангару", region: "Красноярск", year: "1972", length: "1.3", type: "Авто", capacity: "11" },
  { name: "Мост через Чулым", region: "Томская область", year: "1995", length: "1.0", type: "Авто", capacity: "7" },
  { name: "Мост через Кеть", region: "Томская область", year: "1989", length: "0.9", type: "Авто", capacity: "6" },
  { name: "Мост через Таз", region: "Ямало-Ненецкий АО", year: "1993", length: "1.2", type: "Авто", capacity: "9" },
  { name: "Мост через Пур", region: "Ямало-Ненецкий АО", year: "1986", length: "1.1", type: "Авто", capacity: "8" },
  { name: "Мост через Надым", region: "Ямало-Ненецкий АО", year: "1990", length: "1.0", type: "Авто", capacity: "7" },
  { name: "Мост через Обь", region: "Ханты-Мансийский АО", year: "1984", length: "1.5", type: "Авто", capacity: "12" },
  { name: "Мост через Иртыш", region: "Ханты-Мансийский АО", year: "1979", length: "1.3", type: "Авто", capacity: "10" },
  { name: "Мост через Конду", region: "Ханты-Мансийский АО", year: "1987", length: "1.1", type: "Авто", capacity: "8" }
];

// Optional alias (не обязательно, но удобно)
const bridgesData = window.bridgesData;
